variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

.base: &base
  image: docker:latest
  before_script:
    - docker info
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  script:
    - docker run --rm --privileged multiarch/qemu-user-static:5.0.0-2 --reset -p yes
    - TAG="${CI_COMMIT_TAG#v}"
    - TAG="${TAG:-${CI_COMMIT_SHA:0:7}}"

    - |
      if [[ "${IS_HASSIO}" = "YES" ]]; then
        BUILD_TO=esphome/esphome-hassio-base-${BUILD_ARCH}
        DOCKERFILE=${BUILD_ARCH}/Dockerfile.hassio
      else
        BUILD_TO=esphome/esphome-base-${BUILD_ARCH}
        DOCKERFILE=${BUILD_ARCH}/Dockerfile
      fi
    - echo "BUILD_TO ${BUILD_TO}"
    - echo "TAG ${TAG}"
    - echo "DOCKERFILE ${DOCKERFILE}"

    - |
      docker build \
        --tag "${BUILD_TO}:${TAG}" \
        --file "${DOCKERFILE}" \
        .
    - docker push ${BUILD_TO}:${TAG}
  services:
    - name: docker:dind
      command: ["--experimental"]
  tags:
    - docker

aarch64-docker:
  <<: *base
  variables:
    BUILD_ARCH: aarch64
    IS_HASSIO: "NO"

aarch64-hassio:
  <<: *base
  variables:
    BUILD_ARCH: aarch64
    IS_HASSIO: "YES"

amd64-docker:
  <<: *base
  variables:
    BUILD_ARCH: amd64
    IS_HASSIO: "NO"

amd64-hassio:
  <<: *base
  variables:
    BUILD_ARCH: amd64
    IS_HASSIO: "YES"

armv7-docker:
  <<: *base
  variables:
    BUILD_ARCH: armv7
    IS_HASSIO: "NO"

armv7-hassio:
  <<: *base
  variables:
    BUILD_ARCH: armv7
    IS_HASSIO: "YES"

i386-docker:
  <<: *base
  variables:
    BUILD_ARCH: i386
    IS_HASSIO: "NO"

i386-hassio:
  <<: *base
  variables:
    BUILD_ARCH: i386
    IS_HASSIO: "YES"
