name: CI

on:
  pull_request:

jobs:
  build-docker:
    name: Build and publish docker containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, i386, armv7, aarch64]
        build_type: ["hassio", "docker"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: python3 gen.py
      - name: Set up env variables
        run: |
          if [[ "${{ matrix.build_type }}" == "hassio" ]]; then
            dockerfile="build/${{ matrix.arch }}/Dockerfile.hassio"
          else
            dockerfile="build/${{ matrix.arch }}/Dockerfile"
          fi

          echo "::set-env name=DOCKERFILE::${dockerfile}"
      - name: Register QEMU binfmt
        run: docker run --rm --privileged multiarch/qemu-user-static:5.0.0-2 --reset -p yes
      - run: |
          docker build \
            --file "${DOCKERFILE}" \
            .
